- targets: ["sui-testnet.nodeinfravalidators.com:9100", "sui-testnet.nodeinfravalidators.com:9184"]
  labels:
    deployment: production
    chain: SUI
    network: testnet
    servicetype: validator
    cloud: Vultr
    region: england
