- targets: ["aptos-testnet.nodeinfra.com:9100", "aptos-testnet.nodeinfra.com:9101"]
  labels:
    direction: external
    deployment: production
    chain: APT 
    network: testnet
    servicetype: npixel_indexer_fullnode

- targets: ["aptos-testnet.nodeinfra.com:8001"]
  labels:
    direction: external
    deployment: production
    chain: APT 
    network: testnet
    servicetype: npixel_indexer_fullnode
    purpose: kong

- targets: ["aptos-testnet.nodeinfra.com:9187"]
  labels:
    direction: external
    deployment: production
    chain: APT 
    network: testnet
    servicetype: npixel_indexer_fullnode
    purpose: postgresql_exporter
