- targets: ["167.179.82.207:9100", "167.179.82.207:9101", "167.179.82.207:9102", "167.179.82.207:9103"]
  labels:
    direction: external
    deployment: test
    chain: APT 
    network: testnet
    servicetype: npixel_multiple_public_fullnode

- targets: ["167.179.82.207:8001"]
  labels:
    direction: external
    deployment: test
    chain: APT 
    network: testnet
    servicetype: npixel_multiple_public_fullnode
    purpose: kong
