- targets: ["aptos-previewnet-validator.nodeinfravalidators.com:9100", "aptos-previewnet-validator.nodeinfravalidators.com:9101"]
  labels:
    direction: external
    deployment: production
    chain: APT
    network: previewnet
    servicetype: validator
