# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# -----------------------------------------------------------------------------
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
# ----------------------------------------- APTOS ------------------------------------------------ 
  - job_name: "ext-prod-APT-mainnet-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-mainnet-validator.yml
      
    static_configs:
      - targets: ["aptosmainnet.mirny.io:9100","aptosmainnet.mirny.io:9101"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: mainnet
          servicetype: validator

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-mainnet-vfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-mainnet-vfn.yml
      
    static_configs:
      - targets: ["aptosmainnetvfn.mirny.io:9100","aptosmainnetvfn.mirny.io:9101"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: mainnet
          servicetype: validator_fullnode

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-mainnet-indexer"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-mainnet-indexer.yml
      
    static_configs:
      - targets: ["aptos-mainnet.nodeinfra.com:9100", "aptos-mainnet.nodeinfra.com:9101"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: mainnet
          servicetype: indexer_fullnode

  # kong
      - targets: ["aptos-mainnet.nodeinfra.com:8001"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: mainnet
          servicetype: indexer_fullnode
          purpose: kong

  # pgexporter    
      - targets: ["aptos-mainnet.nodeinfra.com:9187"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: mainnet
          servicetype: indexer_fullnode
          purpose: postgresql_exporter

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-testnet-npixelindexer"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-testnet-npixelindexer.yml

    static_configs:
      - targets: ["aptos-testnet.nodeinfra.com:9100", "aptos-testnet.nodeinfra.com:9101"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: testnet
          servicetype: npixel_indexer_fullnode

      - targets: ["aptos-testnet.nodeinfra.com:8001"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: testnet
          servicetype: npixel_indexer_fullnode
          purpose: kong

      - targets: ["aptos-testnet.nodeinfra.com:9187"]
        labels:
          direction: external
          deployment: production
          chain: APT 
          network: testnet
          servicetype: npixel_indexer_fullnode
          purpose: postgresql_exporter
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-test-APT-testnet-npixelpfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-test-APT-testnet-npixelpfn.yml

    static_configs:
      - targets: ["15.165.48.102:9101", "15.165.48.102:9100", "3.38.42.40:9100", "3.38.42.40:9101", "34.81.96.34:9101", "34.81.96.34:9100"]
        labels:
          direction: external
          deployment: test
          chain: APT 
          network: testnet
          servicetype: npixel_public_fullnode

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-test-APT-testnet-npixelmultipfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-test-APT-testnet-npixelmultipfn.yml

    static_configs:
      - targets: ["167.179.82.207:9100", "167.179.82.207:9101", "167.179.82.207:9102", "167.179.82.207:9103"]
        labels:
          direction: external
          deployment: test
          chain: APT 
          network: testnet
          servicetype: npixel_multiple_public_fullnode

      - targets: ["167.179.82.207:8001"]
        labels:
          direction: external
          deployment: test
          chain: APT 
          network: testnet
          servicetype: npixel_multiple_public_fullnode
          purpose: kong

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-previewnet-validator"
  
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-previewnet-validator.yml

    static_configs:
      - targets: ["aptos-previewnet-validator.nodeinfravalidators.com:9100", "aptos-previewnet-validator.nodeinfravalidators.com:9101"]
        labels:
          direction: external
          deployment: production
          chain: APT
          network: previewnet
          servicetype: validator


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-previewnet-vfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-previewnet-vfn.yml

    static_configs:
      - targets: ["aptos-previewnet-vfn.nodeinfravalidators.com:9100", "aptos-previewnet-vfn.nodeinfravalidators.com:9101"]
        labels:
          direction: external
          deployment: production
          chain: APT
          network: previewnet
          servicetype: validator_fullnode


# ----------------------------------------- Nine Chronicles Gold  ------------------------------------------------ 
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-NCG-mainnet-headless"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-NCG-mainnet-headless.yml

    static_configs:
  # ninechronicles headless
      - targets: ["tky-nc-1.ninodes.com:9100"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: headless
          region: tokyo

      - targets: ["sgp-nc-1.ninodes.com:9100"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: headless
          region: singapore

      - targets: ["nj-nc-1.ninodes.com:9100"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: headless
          region: new_jersey
            
      - targets: ["la-nc-1.ninodes.com:9100"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: headless
          region: los_angeles

      - targets: ["fra-nc-1.ninodes.com:9100"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: headless
          region: frankfrut

      - targets: ["backup-nc-1.ninodes.com:9100"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: headless
          purpose: backup

  # ninechronicles graphql custom metrics
      - targets: ["13.124.239.97:8080"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: headless
          purpose: graphql_metric

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-NCG-mainnet-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-NCG-mainnet-validator.yml

    static_configs:
  #ninechronicles validator            
      - targets: ["nc-val.ninodes.com:9100"]
        labels:
          direction: external
          deployment: production
          chain: NCG 
          network: mainnet
          servicetype: validator
            


# ----------------------------------------- SUI  ------------------------------------------------ 
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-SUI-testnetwave3-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-SUI-testnetwave3-validator.yml
          
    static_configs:
      # what is 9184 port?
      - targets: ["sui-testnet.nodeinfravalidators.com:9100", "sui-testnet.nodeinfravalidators.com:9184"]
        labels:
          direction: external
          deployment: production
          chain: SUI
          network: testnetwave3
          servicetype: validator


# ----------------------------------------- HAVAH  ------------------------------------------------ 
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-HVH-mainnet-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-HVH-mainnet-validator.yml
        
    static_configs:
  # havah validator mainnet
      - targets: ["148.113.152.33:9100", "13.124.239.97:8080"]
        labels:
          direction: external
          deployment: production
          chain: HVH 
          network: mainnet
          servicetype: validator


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "int-prod-prometheus"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/int-prod-prometheus.yml
        
  # healthcheck itself
    static_configs:
      - targets: ["localhost:9090", "localhost:9100"]
        labels:
          direction: internal
          deployment: prod
          purpose: prometheus
          region: seoul


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "int-test"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/int-test.yml

    static_configs:
      - targets: []



