# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prom-self"
    static_configs:
            - targets: ["localhost:9090", "localhost:9100"] 
 

  - job_name: "pgexporter"
    static_configs:
            - targets: ["aptos-mainnet.nodeinfra.com:9187", "aptos-testnet.nodeinfra.com:9187"]


  - job_name: "aptos_indexer"
    static_configs:
            - targets: ["aptos-mainnet.nodeinfra.com:9100", "aptos-mainnet.nodeinfra.com:9101", "aptos-testnet.nodeinfra.com:9100", "aptos-testnet.nodeinfra.com:9101"]
                  #lables: 
                        #                                chain_name: "aptos"

              
  - job_name: "mainnet"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
            - targets: ["aptosmainnet.mirny.io:9101","aptosmainnet.mirny.io:9100","aptosmainnetvfn.mirny.io:9101","aptosmainnetvfn.mirny.io:9100"]


  - job_name: "aptosllt"
    static_configs:
      - targets: ["aptosllt.mirny.io:9100","aptosllt.mirny.io:9101","aptoslltvfn.mirny.io:9101","aptoslltvfn.mirny.io:9100"]
                #labels:
                #chain: "ait3"


  - job_name: "9c-Mainnet"
    static_configs:
            - targets: ["tky-nc-1.ninodes.com:9100", "sgp-nc-1.ninodes.com:9100", "nj-nc-1.ninodes.com:9100", "la-nc-1.ninodes.com:9100", "fra-nc-1.ninodes.com:9100", "13.124.239.97:8080", "nc-val.ninodes.com:9100", "backup-nc-1.ninodes.com:9100"]


  - job_name: "Sui-validator-game"
    static_configs:
            - targets: ["15.235.85.218:8080"]
    #     dns_sd_configs:
    #  - refresh_interval: 15s
    #    names:
    #      - 'tky-nc-1.ninodes.com'
    #      - 'sgp-nc-1.ninodes.com'
    #      - 'nj-nc-1.ninodes.com'
    #      - 'la-nc-1.ninodes.com'
    #      - 'fra-nc-1.ninodes.com'
    #  - type: 'A'
    #  - port: '9100'


  - job_name: "hvh-validator"
    static_configs:
      - targets: ["148.113.152.33:9100", "148.113.152.33:9101"]
      #labels:
              #chain: "proxy"


  - job_name: "haproxy"
    static_configs:
      - targets: ["aptosmainnet.mirny.io:9102"]
      #labels:
              #chain: "proxy"

  - job_name: "sui-testnet"
    static_configs:
      - targets: ["sui-testnet.nodeinfravalidators.com:9100", "sui-testnet.nodeinfravalidators.com:9184"]


  - job_name: "kong-aptos-mainnet"
    static_configs:
      - targets: ["aptos-mainnet.nodeinfra.com:9100","aptos-mainnet.nodeinfra.com:8001","aptos-mainnet.nodeinfra.com:9101"]


  - job_name: "kong-aptos-testnet"
    static_configs:
      - targets: ["aptos-testnet.nodeinfra.com:9100","aptos-testnet.nodeinfra.com:8001", "aptos-testnet.nodeinfra.com:9101"]

  - job_name: "npixel-multiple-node-test"
    static_configs:
      - targets: ["167.179.82.207:9100", "167.179.82.207:8001", "167.179.82.207:9101"]


  - job_name: "npixel-test-pfn"
    static_configs:
      - targets: ["npixel-test.ninodes.com:9100", "npixel-test.ninodes.com:8001", "npixel-test.ninodes.com:9101"]

  - job_name: "aptos-previewnet"
    static_configs:
      - targets: ["aptos-previewnet-validator.nodeinfravalidators.com:9100", "aptos-previewnet-validator.nodeinfravalidators.com:9101", "aptos-previewnet-vfn.nodeinfravalidators.com:9100", "aptos-previewnet-vfn.nodeinfravalidators.com:9101"]

  - job_name: "npixel-testnet"
    static_configs:
            - targets: ["15.165.48.102:9101", "15.165.48.102:9100", "3.38.42.40:9100", "3.38.42.40:9101", "34.81.96.34:9101", "34.81.96.34:9100", "167.179.82.207:9100", "167.179.82.207:9101", "167.179.82.207:9102", "167.179.82.207:9103"]

  - job_name: "sui-testnet-fullnode"
    static_configs:
            - targets: ["131.153.159.25:9184", "131.153.159.25:9100"]
