# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# -----------------------------------------------------------------------------
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
# ----------------------------------------- APTOS ------------------------------------------------ 
  - job_name: "ext-prod-APT-mainnet-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-mainnet-validator.yml
      
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-mainnet-vfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-mainnet-vfn.yml
      
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-mainnet-indexer"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-mainnet-indexer.yml
      

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-testnet-npixelindexer"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-testnet-npixelindexer.yml

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-test-APT-testnet-npixelpfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-test-APT-testnet-npixelpfn.yml


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-test-APT-testnet-npixelmultipfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-test-APT-testnet-npixelmultipfn.yml


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-previewnet-validator"
  
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-previewnet-validator.yml



# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-APT-previewnet-vfn"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-APT-previewnet-vfn.yml



# ----------------------------------------- Nine Chronicles Gold  ------------------------------------------------ 
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-NCG-mainnet-headless"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-NCG-mainnet-headless.yml


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-NCG-mainnet-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-NCG-mainnet-validator.yml



# ----------------------------------------- SUI  ------------------------------------------------ 
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-SUI-testnetwave3-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-SUI-testnetwave3-validator.yml
          


# ----------------------------------------- HAVAH  ------------------------------------------------ 
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "ext-prod-HVH-mainnet-validator"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/ext-prod-HVH-mainnet-validator.yml
        


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "int-prod-prometheus"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/int-prod-prometheus.yml
        


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - job_name: "int-test"
    file_sd_configs:
      - files:
        - /home/ubuntu/nodeinfra-prometheus/file_sd/int-test.yml

    static_configs:
      - targets: []



