---
# havah testnet citizen
- targets: ["havah-veganet.nodeinfra.com", "131.153.11.183:9100"]
  labels:
    deployment: production
    chain: HVH 
    network: veganet
    servicetype: citizen
    cloud: PhoenixNAP
    region: phoenix
    node_name: prod_HVH_veganet_api_phx_1
