# ---------------------------------- sui mainnet fullnode
- targets: ["57.128.98.9:9100", "57.128.98.9:9184", "57.128.98.9:8001"]
  labels:
    deployment: production
    chain: SUI
    network: mainnet
    servicetype: fullnode
    cloud: OVH
    region: france
    node_name: prod_SUI_mainnet_fullnode_fra_1