- targets: ["131.153.203.167:9100", "131.153.203.167:8080", "aptos-testnet-econia.nodeinfra.com"]
  labels:
    deployment: production
    chain: APT
    network: testnet
    servicetype: econia_indexer
    cloud: PhoenixNAP
    region: phoenix
    node_name: prod_ECO_testnet_indexerFullnode_phx_1

- targets: ["125.253.92.101:9100", "125.253.92.101:8080", "aptos-testnet-econia.nodeinfra.com"]
  labels:
    deployment: production
    chain: APT
    network: testnet
    servicetype: econia_indexer
    cloud: PhoenixNAP
    region: singapore
    node_name: prod_ECO_testnet_indexerFullnode_sgp_1
