---
- targets: ["13.124.239.97:8180"]
  labels:
    deployment: production
    chain: APT
    purpose: custom_metric

- targets: ["13.124.239.97:8280"]
  labels:
    deployment: production
    chain: SUI
    purpose: custom_metric

- targets: ["13.124.239.97:8380"]
  labels:
    deployment: production
    chain: NCG
    purpose: custom_metric

- targets: ["13.124.239.97:8480"]
  labels:
    deployment: production
    chain: HVH
    purpose: custom_metric

# ----------------------------------------- Upgrade Message ------------------------------------------------
- targets: ["13.124.239.97:8080"]
  labels:
    deployment: production
    purpose: update_message
