---
## Ethereum Lido obol
- targets: ["104.199.220.82:9100", "104.199.220.82:8080", "104.199.220.82:3620"]
  labels:
    deployment: production
    chain: ETH
    network: holesky
    servicetype: validator
    cloud: GCP
    region: taiwan
    node_name: prod_ETH_holeskyTestnet_validator_twn_1
    purpose: obol

- targets: ["104.199.220.82:5054"]
  labels:
    deployment: production
    chain: ETH
    network: holesky
    servicetype: validator
    sub_servicetype: consensus_client
    cloud: GCP
    region: taiwan
    node_name: prod_ETH_holeskyTestnet_validator_twn_1
    purpose: obol
