---
# havah validator mainnet
- targets: ["104.198.0.186:9100", "104.198.0.186:9000"]
  labels:
    deployment: production
    chain: HVH
    network: mainnet
    servicetype: validator
    cloud: gcp
    region: oregon
    node_name: prod_HVH_mainnet_validator_org_1

- targets: ["34.126.71.143:9100", "34.126.71.143:9000"]
  labels:
    deployment: production
    chain: HVH
    network: mainnet
    servicetype: validator
    purpose: backup
    cloud: gcp
    region: singapore
    node_name: prod_HVH_mainnet_validator_backup_sgp_1
